name: Input test workflow

on:
  workflow_dispatch:
    inputs:
      currentVersion:
        description: 'Current version:'
        type: string
        default: $(cat testversion)
      q1:
        description: Bump version?
        type: choice
        required: true
        default: 'No'
        options:
          - 'Yes'
          - 'No'
          - 'Manual bump'
      q2:
        description: 'Type build number(only for manual):'
        type: string
        required: false
      q3:
        description: 'Type version(only for manual):'
        type: string
        required: false

jobs:
  Call:
    uses: ./.github/workflows/called.yml
    with:
      q1: ${{ inputs.q1 }}
      q2: ${{ inputs.q2 }}
      q3: ${{ inputs.q3 }}
