name: Check

on:
  workflow_dispatch:
    inputs:
      q1:
        description: Bump version?
        type: choice
        required: true
        default: 'No'
        options:
          - 'Yes'
          - 'No'
          - 'Manual bump'
      q2:
        description: 'Type build number(only for manual):'
        type: text
        required: false
      q3:
        description: 'Type version(only for manual):'
        type: text
        required: false
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: start script
      run: |
        echo ${{ vars.CUM_IN_MOUSE }} > output.txt
        chmod +x scripts/onetwo.sh
        bash scripts/onetwo.sh < output.txt
