name: CI/CD

on:
  workflow_call:
    inputs:
      REGISTRY:
        default: 'ghcr.io'
        required: true
        type: string
      IMAGE_NAME:
        type: string
      PORT:
        type: string
      CONTAINER:
        type: string
      branch:
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      BOT_TOKEN:
        required: true      
    
jobs:
  CI:
    
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      version: ${{ steps.tag.outputs.new_version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.BOT_TOKEN }}
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Version autogeneration
        id: tag        
        run: |
          chmod +x ./scripts/generate_version.sh
          bash ./scripts/generate_version.sh
                   
      - name: Build docker image
        run: docker build -f ./Dockerfile --platform=linux/amd64 --tag ghcr.io/rsadevops/hulitinerabotaesh/${{ inputs.branch }}:${{ steps.tag.outputs.new_version }} .
        
      - name: Push docker image
        run: docker push ghcr.io/rsadevops/hulitinerabotaesh/${{ inputs.branch }}:${{ steps.tag.outputs.new_version }}
        
      - name: Auto delete old images
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'hulitinerabotaesh/main'
          package-type: 'container'
          min-versions-to-keep: 5
          
  CD:
  
    runs-on: self-hosted
    needs: [CI]
    
    steps:
      - name: Pull Docker images
        run: docker pull ghcr.io/rsadevops/hulitinerabotaesh/${{ inputs.branch }}:${{ needs.CI.outputs.version }}
        
      - name: Remove old container
        run: docker rm -f ${{ inputs.CONTAINER }} || true
        
      - name: Docker container start
        run: docker run -d -e NEW_RELIC_LICENSE_KEY=59663c86e752ee785745160bf9ec06eeFFFFNRAL -e NEW_RELIC_APP_NAME="my-test-app" -p ${{ inputs.PORT }} --name ${{ inputs.CONTAINER }} ghcr.io/rsadevops/hulitinerabotaesh/${{ inputs.branch }}:${{ needs.CI.outputs.version }}
