name: CI/CD

on:
  workflow_call:
    inputs:
      REGISTRY:
        default: 'ghcr.io'
        required: true
        type: string
      IMAGE_NAME:
        type: string
      PORT:
        type: string
      CONTAINER:
        type: string
      branch:
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
        
    
jobs:
  CI:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Version autogeneration
        id: tag
        run: |
          chmod +x ./scripts/generate_version.sh
          bash ./scripts/generate_version.sh ${{ GITHUB_ACTOR }}
      
      - name: Build docker image
        run: docker build -f .Dockerfile --platform=linux/amd64 --tag ghcr.io/hulitinerabotaesh/${{ steps.tag.outputs.new_version }}:latest .
        
      - name: Push docker image
        run: docker push ghcr.io/hulitinerabotaesh/${{ steps.tag.outputs.new_version }}:latest
        
          
  CD:
  
    runs-on: self-hosted
    needs: [CI]
    
    steps:
      - name: Pull Docker images
        run: docker pull ghcr.io/hulitinerabotaesh/${{ steps.tag.outputs.new_version }}:latest
        
      - name: Remove old container
        run: docker rm -f ${{ inputs.CONTAINER }} || true
        
      - name: Docker container start
        run: docker run -d -p ${{ inputs.PORT }} --name ${{ inputs.CONTAINER }} ghcr.io/hulitinerabotaesh/${{ steps.tag.outputs.new_version }}:latest
