name: Decode
on:
  workflow_dispatch:

jobs:
  Decode:
    runs-on: ubuntu-latest
    steps:
    - name: Decode
      env:
        TEST_ENV: ${{ secrets.DECODE_TEST }}
      run: |
        echo -n "$TEST_ENV" | base64 -d > "$SERVICE_ACCOUNT_JSON"
