name: MAIN
on:
  workflow_dispatch:
    
  #push:
  # branches: main
      
jobs:
  call-reuse-workflow:
    uses: rsadevops/hulitinerabotaesh/.github/workflows/ci-cd.yml@main
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      VERSION: main
      PORT: '80:80'
    secrets: 
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
