name: MAIN
on:
  workflow_dispatch:
    inputs: 
      q1:
        description: 'Bump version?'
        required: true
        default: 'no'
        type: choice
        options:
         - 'yes'
         - 'no'
      q2:
        description: Manual bump
        required: false
        type: text
          
jobs:
  call-reuse-workflow:
    name: Call CI/CD action
    uses: ./.github/workflows/ci-cd.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PORT: '80:80'
      CONTAINER: main_build
      branch: main
    secrets: 
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
