name: MAIN

on:
  push:
    branches: main
      
jobs:
  call-reuse-workflow:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/ci-cd.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      VERSION: main
      PORT: '80:80'
    secrets: 
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
