name: MAIN
on:
  push:
    branches: ['main']
  workflow_dispatch:
    
  #push:
  # branches: main
      
jobs:
  call-reuse-workflow:
    name: Call CI/CD action
    uses: ./.github/workflows/ci-cd.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      VERSION: main
      PORT: '80:80'
      CONTAINER: dev_build
    secrets: 
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
