name: MAIN
on:
  push:
    branches: ['main']
  workflow_dispatch:
          
jobs:
  call-reuse-workflow:
    name: Call CI/CD action
    uses: ./.github/workflows/ci-cd.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PORT: '80:80'
      CONTAINER: main_build
      branch: main
    secrets: 
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    #  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
