name: Maintenance mode

on: [workflow_dispatch]

jobs:
  Enable-maintenance-mode:
    runs-on: self-hosted
    steps:
       - name: Where i am?
         run: |
           cd ~/linktest/dir2/
           rm somefile.conf
           ln -s ~/linktest/dir1/secondfile.conf
           ls -lia
