name: Packages cleanup

on: 
    workflow_dispatch: 

jobs:
    Cleanup:
        name: Initiate OS
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: |
                apt-get update -y && apt-get upgrade -y
                pip3 install sys requests
                pip freeze
                pip3 freeze
                pip list
                pip3 list
