name: Packages cleanup

on: 
    workflow_dispatch: 

jobs:
    Cleanup:
        name: Initiate OS
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: |
                pwd
                ls
                chmod +x scripts/packages_cleanup.py
                py scripts/packages_cleanup.py 'work'
