name: Packages cleanup

on: 
    workflow_dispatch: 

jobs:
    Cleanup:
        name: Initiate OS
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
            - name: Install dependencies
              run: |
                chmod +x ./scripts/packages_cleanup.py
                python ./scripts/packages_cleanup.py 'work'
